### PR TITLE
new

### PR DESCRIPTION
**Pull request by kawpls**

### CODE REVIEW

**Comment by McNerdius** [comment]
Not sure what the intent of the PR was - surely not deleting 9 key files and downgrading from the goodness of .NET 6 ?  (Note I don't have TailBlazorLite on Azure Static Web Apps, but .NET 6 works fine there, see [here](https://polite-sky-006af1d1e.azurestaticapps.net/))

**Comment by kawpls** [comment]
sorry man im kinda new to github but i have some questions , would you be down to have a discord call?i really need help with setting up blazor with tailwind on azure static sites. my issue is when i have then locally it works and loads the blazor.webassembly.js but when i host on azure it doesnt find it.

**Comment by McNerdius** [comment]
Looking at your Actions logs, it's about how static web apps does the build & auto-detecting what framework you're using.  It sees the `package.json` and goes with that, skipping anything .NET related.  The static web apps copies `wwwroot` over - that works fine - but the Blazor-related files were never compiled and thus aren't in `wwwroot`, so the references to them in `wwwroot/index.html` will result in a 404.  I've cobbled together what the `steps` portion of the workflow file might look like [on gist](https://gist.githubusercontent.com/McNerdius/1d43655556d2fe0a291773d237791404/raw/cbe71179db5deb8ab8b7cea60a90e6d58b7dfb79/gistfile1.txt) 

I think i'll go ahead and put a static web app for this as a basic version, and update the readme pointing out the essential changes.  

I've got discord installed but have no clue how the calls thing works to be honest.  I'm McNerdius on there as well.

**Comment by kawpls** [comment]
thanks man i will try with what u pointed out

**Comment by McNerdius** [comment]
hey i just put it up as a static web app... here's the [yaml file](https://github.com/McNerdius/TailBlazorLite/blob/main/.github/workflows/azure-static-web-apps-ambitious-smoke-036564410.yml) for it and the [site itself](https://ambitious-smoke-036564410.azurestaticapps.net/)

**Comment by kawpls** [comment]
Thanks man, I think I got it to work correctly after using many of your
configurations. I am really grateful you are awesome.

**Pull request closed without merging**
